# Generated by Django 3.2 on 2022-06-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('correct_alternative', models.IntegerField()),
                ('alternatives', models.ManyToManyField(blank=True, related_name='multiple_choice', to='core.Question')),
            ],
        ),
    ]
