# Generated by Django 3.2 on 2022-06-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220628_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='answers',
        ),
        migrations.AddField(
            model_name='exercise',
            name='answers',
            field=models.ManyToManyField(blank=True, to='core.Answer'),
        ),
    ]
