# Generated by Django 3.2 on 2022-06-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220628_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_selected',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='alternative_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='from_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercise'),
        ),
    ]
