# Generated by Django 3.2 on 2022-06-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exerciselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='correct',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
